// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltjhhdykxltlyjeofjcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0amhoZHlreGx0bHlqZW9mamNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5MTMzNDcsImV4cCI6MjA4NTQ4OTM0N30.IGUQEMUbdvWQW_7UQEylkutKVepUfjaK2mqbQmULSFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});